/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tmk;

import java.awt.Dimension;
import java.awt.Toolkit;
import static java.awt.image.ImageObserver.HEIGHT;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Numan
 */
public class Play extends javax.swing.JFrame {

    /**
     * Creates new form play
     */
    public Play() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Taş-Kağıt-Makas Oyunu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Taş", "Kağıt", "Makas" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 11, 99, 37));

        jButton1.setText("Oyna");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 116, 99, 39));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tmk/rock2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 0, -1, 180));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tmk/paper2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 11, -1, 150));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tmk/scissors2.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 0, -1, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int kullanici=jComboBox1.getSelectedIndex();
        Workers pc=new Workers();
        int pc_secim=pc.pc_secim();
        String message=" ";
        if(pc_secim==1)
            message=String.format("\nSeçiminiz:%s\nBilgisayar Seçimi:Taş",jComboBox1.getSelectedItem());
        else if(pc_secim==2)
            message=String.format("\nSeçiminiz:%s\nBilgisayar Seçimi:Kağıt",jComboBox1.getSelectedItem());
        else if(pc_secim==3)
            message=String.format("\nSeçiminiz:%s\nBilgisayar Seçimi:Makas",jComboBox1.getSelectedItem());     
        if(kullanici==0&&pc_secim==1)
            JOptionPane.showMessageDialog(rootPane,"Berabere!"+message, "Sonuç", HEIGHT);
        else if(kullanici==0&&pc_secim==2)
            JOptionPane.showMessageDialog(rootPane,"Kaybettiniz!"+message, "Sonuç", HEIGHT);
        else if(kullanici==0&&pc_secim==3)
            JOptionPane.showMessageDialog(rootPane,"Kazandınız!"+message, "Sonuç", HEIGHT);
        else if(kullanici==1&&pc_secim==1)
            JOptionPane.showMessageDialog(rootPane,"Kazandınız!"+message, "Sonuç", HEIGHT);
        else if(kullanici==1&&pc_secim==2)
            JOptionPane.showMessageDialog(rootPane,"Berabere!"+message, "Sonuç", HEIGHT);
        else if(kullanici==1&&pc_secim==3)
            JOptionPane.showMessageDialog(rootPane,"Kaybettiniz!"+message, "Sonuç", HEIGHT);
        else if(kullanici==2&&pc_secim==1)
            JOptionPane.showMessageDialog(rootPane,"Kaybettiniz!"+message, "Sonuç", HEIGHT);
        else if(kullanici==2&&pc_secim==2)
            JOptionPane.showMessageDialog(rootPane,"Kazandınız!"+message, "Sonuç", HEIGHT);
        else if(kullanici==2&&pc_secim==3)
            JOptionPane.showMessageDialog(rootPane,"Berabere!"+message, "Sonuç", HEIGHT);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Play().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
